ibexa/fieldtype-matrix

- src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
> IBX-1334: Rebranded ibexa/fieldtype-matrix to use new namespaces

- src/bundle/Resources/config/services/command.yaml
- src/bundle/Resources/config/services/fieldtype.yaml
- tests/lib/CoreSetupFactoryTrait.php
> IBX-1853: Rebranded services names

- src/bundle/Resources/config/kernel.yaml
> IBX-1210: Rebranded @ezdesign ibexa/fieldtype-matrix repository

- package.json
- src/bundle/Resources/public/js/scripts/admin.contenttype.matrix.js
- src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js
JIRA ref: https://issues.ibexa.co/browse/IBX-2435
> IBX-2435: As a developer, I want to have js prettier used in code

- .eslintrc.json
- .github/workflows/frontend.yaml
- package.json
JIRA ref: https://issues.ibexa.co/browse/IBX-2677
Set version for eslint-ibexa-config and fix prettier issues
> IBX-2677: As a developer I want to have prettier and eslint style check/fix

- .github/workflows/browser-tests.yaml
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig
JIRA ref: https://issues.ibexa.co/browse/IBX-3973
> IBX-3973: Nontranslatable and disabled fields are not greyed out in content editing UI

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-6314
> IBX-6314: Apply microcopy guidelines and adjust translation keys and domains

- package.json
JIRA ref: https://issues.ibexa.co/browse/IBX-7315
> IBX-7315: Update eslint/prettier to newest versions

- composer.json
- tests/lib/Repository/SearchServiceTest.php
| :ticket: Issue | IBX-8121 |
This PR fixes code style issues for Ibexa DXP 5.0.
> IBX-8121: Fixed code style for 5.0

- tests/integration/Kernel.php
> IBX-8137: Dropped swiftmailer

- src/bundle/Resources/config/kernel.yaml
> IBX-8533: Replaced deprecated config key

- src/bundle/Command/MigrateLegacyMatrixCommand.php
| :ticket: Issue | IBX-8138 |
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
> IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

- src/lib/GraphQL/Schema/MatrixFieldDefinitionMapper.php
| :ticket: Issue | IBX-8536 |
- https://github.com/ibexa/graphql/pull/71
> IBX-8536: Dropped deprecated graphql interface from implementation

- src/bundle/Resources/public/js/scripts/admin.contenttype.matrix.js
| :ticket: Issue | [IBX-8114](https://issues.ibexa.co/browse/IBX-8114) |
> IBX-8114: Cannot clear input data on create new field type matrix form

- composer.json
- phpstan-baseline.neon
- src/bundle/Command/MigrateLegacyMatrixCommand.php
- src/lib/Form/Transformer/FieldTypeModelTransformer.php
- tests/lib/LegacySetupFactory.php
> [!CAUTION]
> # Merge together with other IBX-8471 Pull Requests
> - [x] Make sure TMP commit(s) are dropped before merging
| :ticket: Issue | IBX-8471 |
Upgrading Symfony dependencies to version 7 along with necessary 3rd party packages and codebase changes.
Key changes:
Sanity tests and/or regression builds.
> IBX-8471: Upgraded codebase to Symfony 7

- src/bundle/Resources/public/scss/fieldType/_ezmatrix.scss
- src/bundle/Resources/public/scss/matrix-content-type.scss
- src/bundle/Resources/public/scss/matrix.scss
> IBX-9940: Removed Sass deprecations

- src/bundle/Resources/config/services/fieldtype.yaml
- src/bundle/Resources/config/services/graphql.yaml
- src/bundle/Resources/encore/ibexa.config.manager.js
- src/bundle/Resources/public/js/scripts/fieldType/ibexa_matrix.js
- src/bundle/Resources/public/scss/fieldType/_ibexa_matrix.scss
- src/bundle/Resources/public/scss/matrix.scss
- src/bundle/Resources/translations/ibexa_fieldtypes.en.xliff
- src/bundle/Resources/translations/ibexa_matrix_fieldtype.en.xliff
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
- src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
- src/bundle/Resources/views/themes/standard/matrix_fieldtype/content_fields.html.twig
- src/lib/FieldType/Mapper/MatrixFormMapper.php
- src/lib/Form/Type/FieldType/MatrixCollectionType.php
- src/lib/Form/Type/FieldType/MatrixEntryType.php
- src/lib/Form/Type/FieldType/MatrixFieldType.php
- src/lib/GraphQL/Schema/MatrixFieldDefinitionInputSchemaWorker.php
- src/lib/GraphQL/Schema/MatrixFieldDefinitionMapper.php
- src/lib/GraphQL/Schema/MatrixFieldDefinitionSchemaWorker.php
- tests/lib/Repository/SearchServiceTest.php
| :ticket: Issue | IBX-9947 |
https://github.com/ibexa/core/pull/543
> IBX-9947: Rebranded field type identifiers

- src/bundle/Command/MigrateLegacyMatrixCommand.php
> IBX-9941: Renamed contentclassattribute_id to content_type_field_definition_id

- src/bundle/Command/MigrateLegacyMatrixCommand.php
- src/lib/FieldType/Mapper/MatrixFormMapper.php
| :ticket: Issue | N/A |
```
Line   src/bundle/Command/MigrateLegacyMatrixCommand.php                      
------ ----------------------------------------------------------------------- 
105    Argument of an invalid type array<SimpleXMLElement>|null supplied for  
foreach, only iterables are supported.                                
🪪  foreach.nonIterable                                                
181    Parameter #1 $cells of method                                          
Ibexa\Bundle\FieldTypeMatrix\Command\MigrateLegacyMatrixCommand::conv  
ertCellsToRows() expects array<int|string, mixed>, array<SimpleXMLEle  
ment>|null given.                                                      
🪪  argument.type …
```
> Fixed PHPStan issues

- .github/workflows/browser-tests.yaml
- .github/workflows/ci.yaml
- .github/workflows/frontend-ci.yaml
> [CI] Adjusted secrets
